create table if not exists public.profiles (
  id uuid primary key,
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.pantry_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'Other',
  shelf_life_days integer not null default 0,
  storage_zone text,
  user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists pantry_items_user_id_idx on public.pantry_items(user_id);
create index if not exists pantry_items_created_at_idx on public.pantry_items(created_at desc);

create table if not exists public.favorite_recipes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  title text not null,
  description text not null default '',
  instructions text not null default '',
  image_url text,
  created_at timestamptz not null default now(),
  constraint favorite_recipes_user_title_key unique (user_id, title)
);

create index if not exists favorite_recipes_user_id_idx on public.favorite_recipes(user_id);
create index if not exists favorite_recipes_created_at_idx on public.favorite_recipes(created_at desc);

create table if not exists public.recipe_favorites (
  user_id uuid not null,
  recipe_title text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, recipe_title)
);

create table if not exists public.recipe_notes (
  user_id uuid not null,
  recipe_title text not null,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, recipe_title)
);

create table if not exists public.shopping_list_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  recipe_title text not null,
  name text not null,
  amount numeric not null default 0,
  unit text not null default 'pcs',
  created_at timestamptz not null default now()
);

create index if not exists shopping_list_items_user_id_idx on public.shopping_list_items(user_id);