-- Persist recipe favorites, personal notes, and shopping list in Supabase

begin;

create table if not exists public.recipe_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_title text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, recipe_title)
);

alter table public.recipe_favorites enable row level security;

drop policy if exists "Users manage own recipe favorites" on public.recipe_favorites;
create policy "Users manage own recipe favorites"
on public.recipe_favorites
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.recipe_notes (
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_title text not null,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, recipe_title)
);

alter table public.recipe_notes enable row level security;

drop policy if exists "Users manage own recipe notes" on public.recipe_notes;
create policy "Users manage own recipe notes"
on public.recipe_notes
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.shopping_list_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_title text not null,
  name text not null,
  amount numeric not null default 0,
  unit text not null default 'pcs',
  created_at timestamptz not null default now()
);

create index if not exists shopping_list_items_user_id_idx on public.shopping_list_items(user_id);

alter table public.shopping_list_items enable row level security;

drop policy if exists "Users manage own shopping list" on public.shopping_list_items;
create policy "Users manage own shopping list"
on public.shopping_list_items
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

commit;